source:      .
destination: ./_site
includes:    ./_includes

markdown:    rdiscount
permalink:   /:title.html

#base_url: http://vlandham.com
base_url: /chrisandemmy
description: ""

rdiscount:
  extensions: []

exclude: []
